use_frameworks!

platform :ios, '8.0'

target 'LYEncrypt_Example' do
  pod 'LYEncrypt', :path => '../'

  target 'LYEncrypt_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
